# Generated by Django 5.2 on 2025-05-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='bithday',
            new_name='birthday',
        ),
    ]
